### ISSUE TITLE
Protocol problem

### ISSUE THREAD

**Issue by FlowerV** [michaelkirsche/6lowpan4omnet-diy#7]
Hi, I have a  question, is the example network running with rpl?

**Comment by michaelkirsche** [comment]
Not under OMNeT, since there is no RPL simulation model included at the moment. I am not sure if there are RPL implementations for INET.

**Comment by FlowerV** [comment]
Without rpl, then what protocol use in organizing the example network on OMNeT topologically??

**Comment by michaelkirsche** [comment]
No protocol is used in this example and in this code base. The old INETMANET framework has issues with IPv6 and MANET routing protocols. Routes are therefore either hardwired or just direct communication is used (direct data transfer between two peers).
